### ISSUE TITLE
Changing topics, joining invite only channels automatically and command recongition in IRC

### ISSUE THREAD

**Issue by holycow131415** [zachbr/Dis4IRC#24]
Hey there,

This project is great because our game server uses many IRC bots that would never work on Discord.

Is it possible if someone changes the topic in IRC... for it to appear in Discord? Right now topic changes dont come through.

Is it also possible if someone types a command in discord... for an IRC bot to recognize it? For example in discord if I type "!time"... the IRC bot doesnt read it.

Lastly, how do i get the IRC bot side of things to auth against nickserv, and join rooms that are invite only automatically?

I've enabled web sockets, and this whole project looks very promising.

**Comment by zachbr** [comment]
Hi, I'm glad you're finding some use for this project as well.

> Is it possible if someone changes the topic in IRC... for it to appear in Discord? Right now topic changes dont come through.

Should be very possible, just needs to be added. This would be feature request.

> Is it also possible if someone types a command in discord... for an IRC bot to recognize it? For example in discord if I type "!time"... the IRC bot doesnt read it.

This is already supported. In the IRC section of the config you will find
```hocon
# Messages that match this regular expression will be passed to IRC without a user prefix
no-prefix-regex="^\\.[A-Za-z0-9]"
```
Messages that match that regular expression will be bridged without the user information (i.e. as commands). The default only matches messages starting with `.` and an A-Z uppercase or lowercase letter or a number. You can modify this regex here and test it at a place like [Regex101](https://regex101.com/).

> Lastly, how do i get the IRC bot side of things to auth against nickserv, and join rooms that are invite only automatically?

You can get the bot to auth with nickserv using the `init-commands-list` under the IRC section. For example, mine looks like this
```hocon
            init-commands-list=[
                "PRIVMSG NickServ IDENTIFY nickserv_name nickserv_password",
                "PRIVMSG NickServ ghost name",
                "PRIVMSG NickServ regain name",
                "MODE DiscordBot +B",
                "MODE DiscordBot +g"
            ]
```
You can also use this make it send itself an invite on networks that require an invite always.

The only hiccup is that this runs _after_ it tries to join the IRC channels. I should probably switch that so that these init commands run _before_. I'll try and do that soon.

**Comment by zachbr** [comment]
Added with GH-35
