### ISSUE TITLE
Messages from Dis -> IRC containing spaces removes the sender's Nickname

### ISSUE THREAD

**Issue by doublehelix457** [zachbr/Dis4IRC#32]
Example: 
DIS: doublehelix457 hello
IRC: \<BotName> \<doublehelix457> hello 

^ Works just as expected

DIS: doublehelix457 How are you?
IRC: \<BotName> how are you?

^ Add spaces, and we have a problem

This is a problem because OUR IRC is linked with other chat services and relies on nicknames being present.

On a semi-related issue, it seems nicknames Dis -> IRC also contain zero width spaces, which shows up on other chat services.

DIS: doublehelix457 hello
IRC: \<BotName> \<doublehelix457> hello
Telegram and other:  \<d ou bl eh el ix 45 7> hello

I thought these issues might be related thus I grouped them together here. I have built from the latest commit on this repo.

**Comment by zachbr** [comment]
The zero width spaces in nicknames is intentional. It’s there to prevent people on Discord with a matching name from pinging themselves constantly on IRC when they speak.
It can be disabled in the config.
```
# Configuration for connecting to the IRC server
irc {
    anti-ping=true # change to false
```

Not sure why nicknames are disappearing in messages with spaces. That’s not something I’ve seen. Will try and take a look at that soon.

**Comment by doublehelix457** [comment]
Thanks for the quick reply

**Comment by zachbr** [comment]
I added more explicit logging to `master` for when the no prefix regex function triggers. As far as I can see that is the only way this should be able to happen.

After building another copy of `master`, change your config's `log-level` to `debug`. (If you have an older config it may be in the config as `debug-logging` which you can set to `true`. Hopefully with the extra debug logs you can pinpoint why this is happening.

**Comment by doublehelix457** [comment]
It seems ive mistaken the `no-prefix-regex` for thinking these were command prefixes. My mistake. Is there a way to specify specific command prefixes?

**Comment by zachbr** [comment]
You would have to clarify exactly what you're asking.

The feature is designed to pattern match messages against a specific regular expression so that bots in IRC can handle it as if there was no bridge, because attaching the username in the message as we do breaks most all of them. What pattern (prefix, exact command match, etc) it uses is up to the host.

**Comment by doublehelix457** [comment]
I was trying to use it to match commands given to IRC from discord so the bot would send the command as if it executed it itself. Is there a way to pattern match command prefixes?

**Comment by zachbr** [comment]
Assuming I'm reading your request properly, that's just a matter of setting the right regular expression.

To match messages that start with a single character followed by a letter or number, for example `!help`, `!remove` `!potato`, `!0` etc , your regex would just be `![a-zA-Z0-9]`

If you wanted to just match a few explicit terms, for example `start`, `stop`, `kill`, your regex would be `start|stop|kill`

It's just important you test your expressions against the messages you want to match to ensure it works as you expect it. Sites like [Regex101](https://regex101.com/) are useful for this.
