### ISSUE TITLE
Make changing the status of the bot optional

### ISSUE THREAD

**Issue by Happylama25** [zachbr/Dis4IRC#68]
When starting the bot, it changes the status to "Playing IRC" 
It would be nice to be able to disable that and/or change the status to a custom one

Adding a config option to toggle would be enough I think

**Comment by zachbr** [comment]
Seems entirely reasonable to me. Will get that on the short list.

**Comment by Happylama25** [comment]
Great! And to add onto this, maybe a feature to set a start/stop message that gets sent in the discord channel for when it connects? Since disabling the status change will not show if the bot is “active” or not

**Comment by zachbr** [comment]
Added in 7530afc662dd9ab671dc35b4db1d035ef11193de

It seems odd that you'd want to hide that the bot is online but still broadcast a message that it is up and running. In most instances I would think it would be obvious fairly quickly whether the bot is working? I am closing this request since the main part is done - if you still want the other thing open a new ticket please.
