### ISSUE TITLE
Bot pings people with numbers as names instead of user

### ISSUE THREAD

**Issue by Phoenix616** [zachbr/Dis4IRC#72]
This ping:
![image](https://github.com/zachbr/Dis4IRC/assets/5768781/3c249aa5-798e-4267-94a1-5ece36da07c5)

Ends up as this on the Discord-side:
![image](https://github.com/zachbr/Dis4IRC/assets/5768781/8a92dab0-518d-457f-9a12-4ff47c8cc021)

User that got pinged instead:
![image](https://github.com/zachbr/Dis4IRC/assets/5768781/3e5bc6fc-2c55-4c33-b3aa-5b653888b636)

No idea how Discord managed to fuck this up or what's the proper way of doing pings now is tbh.

**Comment by zachbr** [comment]
The instance I host was one commit behind (on ced7638b846f3036aaf7a8294b4fb5c782684400), even though I updated JDA with bc05f2238ba5f36b698343c0d8a6886c4934e043 to try and head off some of this. I cannot reproduce this on a guild on master, but I can repro it in Paper's. My guess is that's the issue here.

I see JDA has another release now as well to fix some of the username stuff as well so I'll grab that in a minute and we'll see. I suspect we will continue to see weird issues related to the username transition for a while though.

**Comment by zachbr** [comment]
Updated my instance to 2305767cda81d0286eecbb3d94660e4e78f47099 and this is working as expected now. Thanks for letting me know.
