### ISSUE TITLE
init-commands-list won't run correctly

### ISSUE THREAD

**Issue by Brottweiler** [zachbr/Dis4IRC#75]
I am trying to use NickServ with the bot (similar to how you do it in https://github.com/zachbr/Dis4IRC/issues/24#issuecomment-473490732), and as troubleshooting steps I made it message me to see how it worked.

The config:
```hocon
init-commands-list=[
    "PRIVMSG Brottweiler Hello",
    "PRIVMSG Brottweiler Hello There",
    "PRIVMSG Brottweiler There"
]
```
The output:
```
19:12 <Enyo> Hello
19:12 <Enyo> There
```
As you can see, it ignores the command that has an additional word, making it impossible to use NickServ. Am I doing something wrong or is this a bug?

**Comment by zachbr** [comment]
Hi. It took me a bit longer than I'd like to remember what was going on here. This is actually just poor documentation in that comment (I'll update it).

Since these are "raw" messages to the IRC server, it expects to see command arguments separated by spaces. When sending a message with spaces as the user, you need to prefix your message with an ASCII colon character (`:`, `0x3a` - [the IRC RFC incorrectly lists it as `0x3b`](https://www.rfc-editor.org/errata/eid4091)) so the server knows you're trying to send a message rather than command arguments. This isn't strictly required in all cases, which is why it can be surprising. I believe there were some ircds that were more tolerant of this than others as well - it's been long enough now that I couldn't name them.

So your example above should technically look like this to send correctly according to IRC:
```hocon
init-commands-list=[
    "PRIVMSG Brottweiler :Hello",
    "PRIVMSG Brottweiler :Hello There",
    "PRIVMSG Brottweiler :There"
]
```

My example from that other comment should actually look like this:
```hocon
init-commands-list=[
    "PRIVMSG NickServ :IDENTIFY nickserv_name nickserv_password",
    "PRIVMSG NickServ :GHOST name",
    "PRIVMSG NickServ :REGAIN name",
    "MODE name +B",
    "MODE name +g"
]
```

When working with the init-commands-list, you may need to check the IRC RFC if things aren't working the way you expect them to. The RFC can be a bit dense if you're not used to reading them (or if you only look at it rarely like me) but it does do a good job covering this sort of thing.

Prefix behavior: https://datatracker.ietf.org/doc/html/rfc2812#section-2.3
PRIVMSG command: https://datatracker.ietf.org/doc/html/rfc2812#section-3.3.1

Let me know if this fixes your issue. Thanks.

**Comment by Brottweiler** [comment]
Perfect! Works like intended, thank you very much for the clarification!
